# Generated by Django 5.2.5 on 2025-08-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentZipCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_fee_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override default delivery fee for this area', max_digits=6, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_coverages', to='delivery.deliveryagent')),
                ('zip_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_coverages', to='locations.ziparea')),
            ],
            options={
                'ordering': ['zip_area__zip_code'],
                'unique_together': {('agent', 'zip_area')},
            },
        ),
    ]
