# Generated by Django 5.2.5 on 2025-09-01 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Loyalty Program', max_length=100)),
                ('points_per_rupee', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per rupee spent', max_digits=5)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to earn points', max_digits=10)),
                ('bronze_threshold', models.PositiveIntegerField(default=0)),
                ('silver_threshold', models.PositiveIntegerField(default=1000)),
                ('gold_threshold', models.PositiveIntegerField(default=2000)),
                ('platinum_threshold', models.PositiveIntegerField(default=3000)),
                ('bronze_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('silver_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=3)),
                ('gold_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('platinum_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('referrer_bonus_points', models.PositiveIntegerField(default=100)),
                ('referee_bonus_points', models.PositiveIntegerField(default=50)),
                ('signup_bonus_points', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_type', models.CharField(choices=[('offer', 'Special Offer'), ('festival', 'Festival Promotion'), ('announcement', 'General Announcement'), ('coupon', 'Coupon Code')], default='offer', max_length=20)),
                ('background_color', models.CharField(default='#ff6b35', help_text='Hex color code (e.g., #ff6b35)', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code (e.g., #ffffff)', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('offer_code', models.CharField(blank=True, help_text='Coupon code users can use', max_length=20)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_location', models.CharField(choices=[('home_top', 'Home Page Top'), ('home_middle', 'Home Page Middle'), ('home_bottom', 'Home Page Bottom'), ('loyalty_dashboard', 'Loyalty Dashboard'), ('checkout', 'Checkout Page')], default='home_top', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this offer can be used', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
