# Generated by Django 5.2.5 on 2025-08-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storezipcoverage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_coverages', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='storezipcoverage',
            name='zip_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_coverages', to='locations.ziparea'),
        ),
    ]
