# Generated by Django 5.2.5 on 2025-09-02 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storezipcoverage_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together={('store', 'user')},
        ),
        migrations.AddField(
            model_name='storestaff',
            name='staff_id',
            field=models.CharField(default='STAFF001', help_text='Unique staff ID for this store', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together={('store', 'staff_id'), ('store', 'user')},
        ),
    ]
