# Generated by Django 5.2.5 on 2025-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_stafforderassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
