# Generated by Django 5.2.5 on 2025-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_agent_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_confirmation_code',
            field=models.CharField(blank=True, help_text='Code for final delivery confirmation', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_qr_code',
            field=models.CharField(blank=True, help_text='QR code generated when packed', max_length=50, null=True),
        ),
    ]
