# Generated by Django 5.2.5 on 2025-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_qr_code',
        ),
        migrations.AddField(
            model_name='order',
            name='handover_code',
            field=models.CharField(blank=True, help_text='6-digit alphanumeric code for store-to-delivery handover', max_length=6, null=True),
        ),
    ]
