# Generated by Django 5.2.5 on 2025-09-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_package_qr_code_order_handover_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_delivery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_handover_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
